name: SimpleMarkers
version: '${project.version}'
main: pl.majlitech.simplemarkers.Main
api-version: '1.13'
commands:
  sm:
    description: SimpleMarkers command
    usage: /<command>
    aliases: [simplemarkers, sm, m, marker]
